# Generated by Django 6.0.7 on 2026-07-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('no_of_people', models.IntegerField()),
                ('amount', models.FloatField()),
                ('message', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('booking_date', models.DateField(null=True)),
                ('time', models.CharField(max_length=20, null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField(null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/user/')),
            ],
        ),
        migrations.CreateModel(
            name='tblcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField()),
                ('category_picture', models.ImageField(null=True, upload_to='static/category/')),
            ],
        ),
        migrations.CreateModel(
            name='tblteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=40, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/team/')),
            ],
        ),
        migrations.AlterField(
            model_name='tblcontact',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='tblproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('discounted_price', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/product/')),
                ('added_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblcategory')),
            ],
        ),
    ]
