# Generated by Django 6.0.7 on 2026-07-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tbl_booking_tbl_feedback_tblcategory_tblteam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblteam',
            old_name='designation',
            new_name='about_chef',
        ),
    ]
